### ISSUE TITLE
path separator

### ISSUE THREAD

**Issue by Ifuhao** [elza2/go-cyclic#8]
core/detector.go uses magic string "/" as path separator, this may not work on Windows. Use os.PathSeparator may be better

**Comment by Ifuhao** [comment]
another similar problem on Windows: 
1. CyclicDetector.NodePackageMap use file path as key, that means it use "\" as path separator. 
2. But import values use "/" as separator constantly. 
3. at line core/detector.go:253.  <code>pkgs := c.NodePackageMap[in]</code>, cannot get anything

**Comment by elza2** [comment]
Thank you for your question,  only run on mac, it has not tried to run on windows, this is my problem, it will be fixed later

**Comment by Ifuhao** [comment]
> Thank you for your question, only run on mac, it has not tried to run on windows, this is my problem, it will be fixed later

Can you give me permission. I have made some modifications, but push permission deny

**Comment by elza2** [comment]
Ok, please wait a while

**Comment by elza2** [comment]
Please try again

**Comment by elza2** [comment]
> > Thank you for your question, only run on mac, it has not tried to run on windows, this is my problem, it will be fixed later
> 
> Can you give me permission. I have made some modifications, but push permission deny

You need to fork to your repository, then commit to your repository, and merge from your repository to that repository

**Comment by Ifuhao** [comment]
> > > Thank you for your question, only run on mac, it has not tried to run on windows, this is my problem, it will be fixed later
> > 
> > 
> > Can you give me permission. I have made some modifications, but push permission deny
> 
> You need to fork to your repository, then commit to your repository, and merge from your repository to that repository

ok

**Comment by elza2** [comment]
#9
